# Generated by Django 4.0.6 on 2022-08-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.TextField(choices=[], max_length=150),
        ),
    ]
